from pathlib import Path

INDEX=Path('index.html')
VOICE=Path('majalis-voice.js')

s=INDEX.read_text()

s=s.replace('v1.13.8','v1.14.0')
s=s.replace('1.13.8','1.14.0')

footer_old='''<div class="site-footer-wrap">\n  <footer class="footer"><span>إعداد نايف المحمدي مستشار الحوكمة وتطوير الأعمال</span><span class="tool-label">منظومة أعمال المجالس | أداة مجالس</span><span class="version">v1.14.0</span><span class="privacy-note">يحفظ الزائر بياناته على جهازه، ويحفظ الوضع الإداري بياناته في Firestore. عند استخدام المساعد يعالج Gemini سياق الاجتماع لتنفيذ الطلب.</span></footer>\n  <span class="social-username">almohammdin</span>\n  <nav class="site-socials" aria-label="حسابات نايف المحمدي">'''
footer_new='''<div class="site-footer-wrap">\n  <footer class="footer">\n    <button class="admin-entry-button footer-admin-entry" id="adminAccessButton" type="button" aria-haspopup="dialog">\n      <span class="admin-entry-icon" aria-hidden="true">⌾</span>\n      <span id="adminAccessLabel">دخول الإدارة</span>\n    </button>\n    <span>إعداد نايف المحمدي مستشار الحوكمة وتطوير الأعمال</span><span class="tool-label">منظومة أعمال المجالس | أداة مجالس</span><span class="version">v1.14.0</span><span class="privacy-note">يحفظ الزائر بياناته على جهازه، ويحفظ الوضع الإداري بياناته في Firestore. عند استخدام المساعد يعالج Gemini سياق الاجتماع لتنفيذ الطلب.</span>\n  </footer>\n  <span class="social-username">almohammdin</span>\n  <nav class="site-socials" aria-label="حسابات نايف المحمدي">'''
if footer_old not in s: raise SystemExit('footer anchor missing')
s=s.replace(footer_old,footer_new,1)
admin_tail='''  <button class="admin-entry-button footer-admin-entry" id="adminAccessButton" type="button" aria-haspopup="dialog">\n    <span class="admin-entry-icon" aria-hidden="true">⌾</span>\n    <span id="adminAccessLabel">دخول الإدارة</span>\n  </button>\n</div>'''
if admin_tail not in s: raise SystemExit('footer admin tail missing')
s=s.replace(admin_tail,'</div>',1)

extra_style='''<style id="majalis-v1140-footer-ballot-closing">\n.site-footer-wrap{position:relative}\n.site-footer-wrap .footer{position:relative;display:flex;align-items:center;justify-content:center;gap:10px 14px;flex-wrap:wrap;min-height:42px;padding-inline:118px}\n.site-footer-wrap .footer-admin-entry{position:absolute;inset-inline-start:14px;top:50%;transform:translateY(-50%);margin:0;white-space:nowrap}\n.minutes-closing-fields{grid-column:1/-1;border:1px solid var(--line);border-radius:14px;background:var(--soft);padding:13px}\n.minutes-closing-fields>strong{display:block;color:var(--navy);font-size:13px;margin-bottom:9px}\n.minutes-closing-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}\n.minutes-closing-sign-toggle{align-self:end;min-height:45px;border:1px solid var(--line);border-radius:11px;background:#fff;padding:9px 11px}\n.minutes-final-block{margin:24px auto 8px;width:min(100%,430px);border-top:1px solid var(--line);padding-top:14px}\n.minutes-final-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 18px}\n.minutes-final-item{min-height:48px}.minutes-final-item span{display:block;color:var(--muted);font-size:9px}.minutes-final-item strong{display:block;color:var(--navy);font-size:11px;margin-top:2px}.minutes-final-signature{grid-column:1/-1}.minutes-final-signature .sign-pad{display:block;height:42px;border-bottom:1px solid #9FA8B4}\n.minutes-default-closing{text-align:center;font-weight:700;color:var(--navy);margin:24px 0 10px;font-size:13px}\n.blank-ballot-note{text-align:center;color:var(--muted);font-size:10px;margin:0 0 10px}\n.blank-ballot-card .ballot-person{display:none!important}\n@media(max-width:760px){.site-footer-wrap .footer{padding-inline:12px;padding-bottom:48px}.site-footer-wrap .footer-admin-entry{top:auto;bottom:4px;inset-inline-start:10px;transform:none}.minutes-closing-grid{grid-template-columns:1fr}}\n@media print{.site-footer-wrap{display:none!important}}\n</style>\n'''
s=s.replace('</head>',extra_style+'</head>',1)

closing_anchor='''          <div class="field w12"><label>خاتمة المحضر <span class="optional-tag">اختياري</span></label><textarea class="control live" id="closingNote" placeholder="اكتب خاتمة المحضر دون عنوان"></textarea><div class="info-help"><span class="info-mark">i</span><span>تظهر بعد جدول المداولات والقرارات دون عنوان مستقل، وتحذف تلقائيا عند تركها فارغة</span></div></div>'''
closing_fields='''          <div class="field w12"><label>خاتمة المحضر <span class="optional-tag">اختياري</span></label><textarea class="control live" id="closingNote" placeholder="اكتب خاتمة المحضر دون عنوان"></textarea><div class="info-help"><span class="info-mark">i</span><span>تظهر بعد جدول المداولات والقرارات دون عنوان مستقل، وتحذف تلقائيا عند تركها فارغة</span></div></div>\n          <div class="minutes-closing-fields">\n            <strong>بيانات ختامية للمحضر <span class="optional-tag">اختياري</span></strong>\n            <div class="minutes-closing-grid">\n              <div><label for="minutesClosingName">الاسم</label><input class="control live" id="minutesClosingName" placeholder="مثال: أحمد محمد"></div>\n              <div><label for="minutesClosingPosition">المنصب</label><input class="control live" id="minutesClosingPosition" placeholder="مثال: رئيس المجلس أو مدير الشركة"></div>\n              <div><label for="minutesClosingDate">التاريخ</label><input class="control live" id="minutesClosingDate" placeholder="مثال: 13 / 08 / 2026"></div>\n              <label class="check-row minutes-closing-sign-toggle"><input type="checkbox" class="live" id="minutesClosingSignature"><span>إضافة خانة توقيع</span></label>\n            </div>\n            <div class="hint">يظهر هذا الجزء في نهاية محضر الاجتماع إذا أدخلت أي عنصر منه.</div>\n          </div>'''
if closing_anchor not in s: raise SystemExit('closing note anchor missing')
s=s.replace(closing_anchor,closing_fields,1)

old_ballot="function ballotParticipantCard(person,index,items){const p=person?normalizeParticipant(person):null;const name=p?.name||'',role=p?.role||'',votes=p?participantVoteTotal(p):0;const participantMeta=`<div class=\"ballot-person\"><div><span>اسم المصوت</span><strong>${esc(name)||'____________________________'}</strong></div><div><span>الصفة</span><strong>${esc(role)||'____________________________'}</strong></div>${ownershipRegisterEnabled()?`<div><span>عدد الأصوات</span><strong class=\"latin-number\">${votes||'________________'}</strong></div><div><span>النسبة من إجمالي حقوق التصويت</span><strong class=\"latin-number\">${percentText(votes,capitalVotesTotal())}</strong></div>`:''}</div>`;const rows=items.length?items.map((item,i)=>`<tr><td>${i+1}</td><td><strong>${esc(item.title||'')}</strong>${item.decision?`<div class=\"ballot-decision\"><strong>القرار المقترح:</strong> ${esc(item.decision)}</div>`:''}</td><td><span class=\"vote-choice\"><span class=\"choice-box\"></span> موافق</span></td><td><span class=\"vote-choice\"><span class=\"choice-box\"></span> غير موافق</span></td><td><span class=\"vote-choice\"><span class=\"choice-box\"></span> ممتنع</span></td></tr>`).join(''):`<tr><td>1</td><td></td><td><span class=\"choice-box\"></span></td><td><span class=\"choice-box\"></span></td><td><span class=\"choice-box\"></span></td></tr>`;return `<section class=\"ballot-card individual-attendance-sheet\">${participantMeta}<table class=\"doc-table ballot-table\"><thead><tr><th>م</th><th>البند محل التصويت</th><th>موافق</th><th>غير موافق</th><th>ممتنع</th></tr></thead><tbody>${rows}</tbody></table><div class=\"signature-grid single-signature-grid\"><div class=\"signature-field\">توقيع المصوت<span class=\"sign-pad\"></span></div></div></section>`}"
new_ballot="function ballotParticipantCard(person,index,items){const p=person?normalizeParticipant(person):null,blank=!p;const name=p?.name||'',role=p?.role||'',votes=p?participantVoteTotal(p):0;const participantMeta=blank?'':`<div class=\"ballot-person\"><div><span>اسم المصوت</span><strong>${esc(name)}</strong></div><div><span>الصفة</span><strong>${esc(role)}</strong></div>${ownershipRegisterEnabled()?`<div><span>عدد الأصوات</span><strong class=\"latin-number\">${votes||0}</strong></div><div><span>النسبة من إجمالي حقوق التصويت</span><strong class=\"latin-number\">${percentText(votes,capitalVotesTotal())}</strong></div>`:''}</div>`;const rows=items.length?items.map((item,i)=>`<tr><td>${i+1}</td><td><strong>${esc(item.title||'')}</strong>${item.decision?`<div class=\"ballot-decision\"><strong>القرار المقترح:</strong> ${esc(item.decision)}</div>`:''}</td><td><span class=\"vote-choice\"><span class=\"choice-box\"></span> موافق</span></td><td><span class=\"vote-choice\"><span class=\"choice-box\"></span> غير موافق</span></td><td><span class=\"vote-choice\"><span class=\"choice-box\"></span> ممتنع</span></td></tr>`).join(''):`<tr><td>1</td><td></td><td><span class=\"choice-box\"></span></td><td><span class=\"choice-box\"></span></td><td><span class=\"choice-box\"></span></td></tr>`;return `<section class=\"ballot-card individual-attendance-sheet ${blank?'blank-ballot-card':''}\">${blank?'<p class=\"blank-ballot-note\">بطاقة تصويت فارغة للاستخدام الورقي</p>':''}${participantMeta}<table class=\"doc-table ballot-table\"><thead><tr><th>م</th><th>البند محل التصويت</th><th>موافق</th><th>غير موافق</th><th>ممتنع</th></tr></thead><tbody>${rows}</tbody></table>${blank?'':`<div class=\"signature-grid single-signature-grid\"><div class=\"signature-field\">توقيع المصوت<span class=\"sign-pad\"></span></div></div>`}</section>`}"
if old_ballot not in s: raise SystemExit('ballot function anchor missing')
s=s.replace(old_ballot,new_ballot,1)
s=s.replace("document.querySelectorAll('#docVoting .ballot-card').forEach(card=>{", "document.querySelectorAll('#docVoting .ballot-card:not(.blank-ballot-card)').forEach(card=>{", 1)

helper="""function minutesFinalBlock(){const name=($('minutesClosingName')?.value||'').trim(),position=($('minutesClosingPosition')?.value||'').trim(),date=($('minutesClosingDate')?.value||'').trim(),signature=!!$('minutesClosingSignature')?.checked;if(!name&&!position&&!date&&!signature)return '';const items=[];if(name)items.push(`<div class=\"minutes-final-item\"><span>الاسم</span><strong>${esc(name)}</strong></div>`);if(position)items.push(`<div class=\"minutes-final-item\"><span>المنصب</span><strong>${esc(position)}</strong></div>`);if(date)items.push(`<div class=\"minutes-final-item\"><span>التاريخ</span><strong>${esc(date)}</strong></div>`);if(signature)items.push(`<div class=\"minutes-final-item minutes-final-signature\"><span>التوقيع</span><span class=\"sign-pad\"></span></div>`);return `<section class=\"minutes-final-block\"><div class=\"minutes-final-grid\">${items.join('')}</div></section>`}\nfunction defaultClosingLine(){return '<div class=\"minutes-default-closing\">والله الموفق</div>'}\n"""
if 'function renderDocuments(){' not in s: raise SystemExit('renderDocuments anchor missing')
s=s.replace('function renderDocuments(){',helper+'function renderDocuments(){',1)

minutes_old="${closingNoteLine}${endLine}</div>`+footer();"
if minutes_old not in s: raise SystemExit('minutes ending anchor missing')
s=s.replace(minutes_old,"${closingNoteLine}${endLine}${minutesFinalBlock()}${defaultClosingLine()}</div>`+footer();",1)

tally_old="</table></div>`+footer();\n }\n refreshMeetingIdentity();updateCompletionIndicators();"
if tally_old not in s: raise SystemExit('tally ending anchor missing')
s=s.replace(tally_old,"</table>${defaultClosingLine()}</div>`+footer();\n }\n refreshMeetingIdentity();updateCompletionIndicators();",1)

INDEX.write_text(s)

v=VOICE.read_text().replace('1.13.8','1.14.0')
v=v.replace("TOOL_TIMEOUT_MS=15000;", "TOOL_TIMEOUT_MS=15000,VOICE_IDLE_TIMEOUT_MS=30000;")
v=v.replace("wakeLockSentinel=null;", "wakeLockSentinel=null,idleTimer=null,lastVoiceActivity=0;",1)
idle_anchor="const emitState=(state,label)=>window.dispatchEvent(new CustomEvent('majalis:voice-state',{detail:{state,label}}));"
idle_code="""const emitState=(state,label)=>window.dispatchEvent(new CustomEvent('majalis:voice-state',{detail:{state,label}}));\nfunction clearIdleTimer(){clearTimeout(idleTimer);idleTimer=null}\nfunction markVoiceActivity(){lastVoiceActivity=Date.now();if(!active)return;clearIdleTimer();idleTimer=setTimeout(()=>{if(active&&Date.now()-lastVoiceActivity>=VOICE_IDLE_TIMEOUT_MS)stop('idle')},VOICE_IDLE_TIMEOUT_MS)}\n"""
if idle_anchor not in v: raise SystemExit('voice idle anchor missing')
v=v.replace(idle_anchor,idle_code,1)
v=v.replace("async function handleToolCalls(calls=[]){const responses=[];setStatus('أنفذ الخطوة…','working');", "async function handleToolCalls(calls=[]){markVoiceActivity();const responses=[];setStatus('أنفذ الخطوة…','working');",1)
v=v.replace("if(content.inputTranscription?.text&&!micSuppressed)setDetail(`أنت: ${content.inputTranscription.text}`);", "if(content.inputTranscription?.text&&!micSuppressed){markVoiceActivity();setDetail(`أنت: ${content.inputTranscription.text}`)}",1)
v=v.replace("if(content.outputTranscription?.text)setDetail(`مساعد مجالس: ${content.outputTranscription.text}`);", "if(content.outputTranscription?.text){markVoiceActivity();setDetail(`مساعد مجالس: ${content.outputTranscription.text}`)}",1)
v=v.replace("function playPcm(base64){if(!active||!outputContext||!outputWorklet||!base64)return;", "function playPcm(base64){if(!active||!outputContext||!outputWorklet||!base64)return;markVoiceActivity();",1)
v=v.replace("async function shutdown(){await releaseWakeLock();clearTimeout(resumeMicTimer);", "async function shutdown(){clearIdleTimer();await releaseWakeLock();clearTimeout(resumeMicTimer);",1)
v=v.replace("if(!active)return;startMic();setStatus('أسمعك الآن','listening');", "if(!active)return;startMic();markVoiceActivity();setStatus('أسمعك الآن','listening');",1)
old_stop="async function stop(){active=false;try{session?.close?.()}catch{}session=null;await shutdown();emitState('','اضغط وقل ما تريد');const host=document.getElementById('majalisVoiceOverlay');if(host)host.hidden=true}"
new_stop="async function stop(reason='manual'){const idle=reason==='idle';active=false;clearIdleTimer();try{session?.close?.()}catch{}session=null;await shutdown();emitState('',idle?'انتهت المحادثة لعدم وجود تفاعل':'اضغط وقل ما تريد');const host=document.getElementById('majalisVoiceOverlay');if(host){if(idle){setStatus('تم إنهاء المحادثة','idle');setDetail('انتهت المحادثة الصوتية بعد 30 ثانية بدون تفاعل.');setTimeout(()=>{if(!active)host.hidden=true},2200)}else host.hidden=true}}"
if old_stop not in v: raise SystemExit('voice stop anchor missing')
v=v.replace(old_stop,new_stop,1)
VOICE.write_text(v)
