import {GoogleGenAI,Modality} from 'https://cdn.jsdelivr.net/npm/@google/genai@2.14.0/+esm';
import {MAJALIS_TOOL_DECLARATIONS,executeMajalisTool} from './majalis-voice-tools.js?v=1.13.3';

const MODEL='gemini-3.1-flash-live-preview',INPUT_RATE=16000,OUTPUT_RATE=24000,TOOL_TIMEOUT_MS=15000;
let active=false,session=null,micStream=null,micContext=null,outputContext=null,micSource=null,micProcessor=null,silentGain=null,outputWorklet=null,outputGain=null,micSuppressed=false,outputQueuedUntil=0,resumeMicTimer=null,streamEndSent=false;
function isIOS(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
const IOS_ECHO_GUARD=isIOS();
const endpoint=()=>String(window.MAJALIS_VOICE_TOKEN_ENDPOINT||'https://mesraah-live-token.naif123456.workers.dev/token').trim();
const emitState=(state,label)=>window.dispatchEvent(new CustomEvent('majalis:voice-state',{detail:{state,label}}));

function contextInstruction(){const context=window.MajalisAssistantBridge?.getPlatformContext?.()||{};return `أنت مساعد مجالس، أمين اجتماع سعودي ذكي داخل منصة مجالس. هذه محادثة صوتية حقيقية وليست قراءة للنصوص.
تكلم بعربية سعودية سهلة ومهنية، واختصر. اسأل سؤالا واحدا فقط كل مرة. افهم هدف المستخدم واقرأ حالة المنصة الحالية قبل أن تشرح أو تقترح.
استخدم get_meeting_context عند الحاجة إلى أحدث البيانات. أنت ترى نوع الجهة والاجتماع والحقول والمشاركين وجدول الأعمال والنواقص والمرحلة الحالية.
استخدم أدوات مجالس للتنقل والتركيز والفحص والتنفيذ. عندما تنتقل إلى حقل، اشرح للمستخدم باختصار ماذا يكتب فيه ولماذا.
اعرض الاقتراح شفهيا واطلب موافقة صريحة قبل تغيير أي حقل أو إضافة مشارك أو بند. حقوق الملكية والتصويت والنصاب وحالة المحضر تحتاج تأكيدا صريحا دائما.
لا تقل تم الحفظ أو أضفت أو عدلت إلا بعد رجوع أداة التعديل بالقيمتين ok=true وpersisted=true. إذا تعذر تأكيد الحفظ فقل ذلك مباشرة. لا تخترع قاعدة أو نسبة أو مدة؛ استخدم explain_requirement فقط.
لا تسرد الصفحة كاملة ولا تقرأ النصوص آليا. تحدث معه وساعده على إنجاز الخطوة الحالية.
حالة المنصة عند بدء المحادثة:
${JSON.stringify(context)}`}
function ensureUi(){if(document.getElementById('majalisVoiceOverlay'))return;const host=document.createElement('div');host.id='majalisVoiceOverlay';host.className='majalis-voice-overlay';host.hidden=true;host.innerHTML=`<section class="majalis-voice-card" role="region" aria-label="محادثة صوتية مع مساعد مجالس"><div class="majalis-voice-bars" aria-hidden="true"><i></i><i></i><i></i></div><div class="majalis-voice-copy"><strong class="majalis-voice-status" id="majalisVoiceLiveStatus" aria-live="polite">جاهز</strong><p id="majalisVoiceDetail">تكلم بشكل طبيعي</p></div><button type="button" class="majalis-voice-stop" id="majalisVoiceStop" aria-label="إنهاء المحادثة">×</button></section>`;document.body.appendChild(host);document.getElementById('majalisVoiceStop').onclick=stop}
function injectStyles(){if(document.getElementById('majalisVoiceStyles'))return;const style=document.createElement('style');style.id='majalisVoiceStyles';style.textContent=`.majalis-voice-overlay{position:fixed;left:0;right:0;bottom:max(10px,env(safe-area-inset-bottom));z-index:200;display:flex;justify-content:center;padding:0 12px;pointer-events:none}.majalis-voice-overlay[hidden]{display:none}.majalis-voice-card{width:min(620px,100%);min-height:56px;display:grid;grid-template-columns:38px minmax(0,1fr) 36px;align-items:center;gap:10px;padding:7px 9px 7px 11px;border:1px solid rgba(234,213,141,.4);border-radius:15px;background:linear-gradient(135deg,#0b1a2b,#173754);box-shadow:0 12px 32px rgba(0,0,0,.24);color:#fff;pointer-events:auto;text-align:right}.majalis-voice-bars{width:36px;height:36px;border-radius:10px;background:rgba(201,168,76,.16);display:flex;align-items:center;justify-content:center;gap:3px}.majalis-voice-bars i{width:3px;height:12px;border-radius:99px;background:#ead58d;animation:majalisVoiceBars .9s ease-in-out infinite}.majalis-voice-bars i:nth-child(2){height:20px;animation-delay:.15s}.majalis-voice-bars i:nth-child(3){animation-delay:.3s}@keyframes majalisVoiceBars{50%{transform:scaleY(.45);opacity:.65}}.majalis-voice-copy{min-width:0}.majalis-voice-status{display:block;font-size:10.5px}.majalis-voice-card p{margin:2px 0 0;color:rgba(255,255,255,.72);font-size:9px;line-height:1.35;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.majalis-voice-stop{width:34px;height:34px;border:1px solid rgba(255,255,255,.18);border-radius:10px;background:rgba(255,255,255,.09);color:#fff;font:inherit;font-size:19px;line-height:1}@media(max-width:520px){.majalis-voice-overlay{padding:0 8px}.majalis-voice-card{min-height:52px;grid-template-columns:34px minmax(0,1fr) 34px;gap:8px;padding:6px 7px}.majalis-voice-bars{width:32px;height:32px}.majalis-voice-stop{width:32px;height:32px}}`;document.head.appendChild(style)}
function setStatus(text,state){const el=document.getElementById('majalisVoiceLiveStatus');if(el)el.textContent=text;emitState(state,text)}
function setDetail(text){const el=document.getElementById('majalisVoiceDetail');if(el)el.textContent=String(text||'')}
function bytesToBase64(bytes){let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
function base64ToFloat32(value){const binary=atob(value),length=binary.length-(binary.length%2),buffer=new ArrayBuffer(length),bytes=new Uint8Array(buffer);for(let i=0;i<length;i++)bytes[i]=binary.charCodeAt(i);const pcm=new Int16Array(buffer),out=new Float32Array(pcm.length);for(let i=0;i<pcm.length;i++)out[i]=pcm[i]/32768;return out}
function resampleToInt16(input,sourceRate){const ratio=sourceRate/INPUT_RATE,out=new Int16Array(Math.max(1,Math.round(input.length/ratio)));for(let i=0;i<out.length;i++){const pos=i*ratio,left=Math.floor(pos),right=Math.min(left+1,input.length-1),mix=pos-left,value=(input[left]||0)*(1-mix)+(input[right]||0)*mix,clamped=Math.max(-1,Math.min(1,value));out[i]=clamped<0?clamped*32768:clamped*32767}return out}
async function prepareAudio(){const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx||!navigator.mediaDevices?.getUserMedia)throw new Error('voice-not-supported');micContext=new AudioCtx();try{outputContext=new AudioCtx({sampleRate:OUTPUT_RATE})}catch{outputContext=new AudioCtx()}await Promise.all([micContext.resume(),outputContext.resume()]);if(!outputContext.audioWorklet)throw new Error('voice-playback-not-supported');await outputContext.audioWorklet.addModule('./majalis-voice-playback.worklet.js?v=1.13.3');outputWorklet=new AudioWorkletNode(outputContext,'majalis-voice-playback');outputGain=outputContext.createGain();outputGain.gain.value=1;outputWorklet.connect(outputGain);outputGain.connect(outputContext.destination);outputQueuedUntil=outputContext.currentTime;micStream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}
function clearPlayback(){try{outputWorklet?.port.postMessage({type:'clear'})}catch{}if(outputContext)outputQueuedUntil=outputContext.currentTime}
function suppressMicForModelOutput(){if(!IOS_ECHO_GUARD||micSuppressed)return;micSuppressed=true;if(!streamEndSent&&session){streamEndSent=true;try{session.sendRealtimeInput({audioStreamEnd:true})}catch{}}}
function resumeMicAfterPlayback(){clearTimeout(resumeMicTimer);if(!IOS_ECHO_GUARD){if(active)setStatus('أسمعك الآن','listening');return}const remainingMs=outputContext?Math.max(0,(outputQueuedUntil-outputContext.currentTime)*1000):0;resumeMicTimer=setTimeout(()=>{micSuppressed=false;streamEndSent=false;if(active)setStatus('أسمعك الآن','listening')},remainingMs+140)}
function playPcm(base64){if(!active||!outputContext||!outputWorklet||!base64)return;suppressMicForModelOutput();const samples=base64ToFloat32(base64);if(!samples.length)return;outputQueuedUntil=Math.max(outputContext.currentTime,outputQueuedUntil)+samples.length/OUTPUT_RATE;try{outputWorklet.port.postMessage({samples},[samples.buffer])}catch{outputWorklet.port.postMessage({samples})}setStatus('مساعد مجالس يتحدث','speaking')}
async function fetchToken(forceRefresh=false){if(typeof window.MajalisVoiceGetAppCheckToken!=='function')throw new Error('voice-app-check-not-ready');const token=await window.MajalisVoiceGetAppCheckToken({forceRefresh}),response=await fetch(endpoint(),{method:'POST',headers:{'Content-Type':'application/json','X-Firebase-AppCheck':token},body:'{}'}),data=await response.json().catch(()=>({}));if(response.status===401&&!forceRefresh)return fetchToken(true);if(!response.ok||!data.token)throw new Error('voice-token-failed');return data.token}
function withTimeout(promise,ms=TOOL_TIMEOUT_MS){let timer;return Promise.race([Promise.resolve(promise),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('voice-tool-timeout')),ms)})]).finally(()=>clearTimeout(timer))}
async function handleToolCalls(calls=[]){const responses=[];setStatus('أنفذ الخطوة…','working');for(const call of calls){let result;try{result=await withTimeout(executeMajalisTool(call.name,call.args||{}))}catch(error){result={ok:false,error:String(error?.message||error)}}responses.push({name:call.name,id:call.id,response:{result}})}session?.sendToolResponse({functionResponses:responses})}
function handleMessage(message){if(message?.toolCall?.functionCalls?.length)handleToolCalls(message.toolCall.functionCalls).catch(console.error);const content=message?.serverContent;if(!content)return;if(content.interrupted){clearPlayback();micSuppressed=false;streamEndSent=false;setStatus('أسمعك الآن','listening')}if(content.inputTranscription?.text&&!micSuppressed)setDetail(`أنت: ${content.inputTranscription.text}`);if(content.outputTranscription?.text)setDetail(`مساعد مجالس: ${content.outputTranscription.text}`);for(const part of content.modelTurn?.parts||[])if(part.inlineData?.data)playPcm(part.inlineData.data);if(content.turnComplete&&active)resumeMicAfterPlayback()}
function startMic(){if(!active||!session||!micContext||!micStream||micProcessor)return;micSource=micContext.createMediaStreamSource(micStream);micProcessor=micContext.createScriptProcessor(2048,1,1);silentGain=micContext.createGain();silentGain.gain.value=0;micProcessor.onaudioprocess=event=>{if(!active||!session||micSuppressed)return;const pcm=resampleToInt16(event.inputBuffer.getChannelData(0),micContext.sampleRate),bytes=new Uint8Array(pcm.buffer,pcm.byteOffset,pcm.byteLength);try{session.sendRealtimeInput({audio:{data:bytesToBase64(bytes),mimeType:`audio/pcm;rate=${INPUT_RATE}`}})}catch{}};micSource.connect(micProcessor);micProcessor.connect(silentGain);silentGain.connect(micContext.destination)}
async function shutdown(){clearTimeout(resumeMicTimer);resumeMicTimer=null;micSuppressed=false;streamEndSent=false;if(micProcessor)micProcessor.onaudioprocess=null;try{micProcessor?.disconnect();micSource?.disconnect();silentGain?.disconnect();outputWorklet?.disconnect();outputGain?.disconnect()}catch{}micStream?.getTracks?.().forEach(track=>track.stop());micStream=null;try{await micContext?.close();await outputContext?.close()}catch{}micContext=outputContext=null;micProcessor=micSource=silentGain=outputWorklet=outputGain=null}
async function start(){
  if(active)return;
  ensureUi();injectStyles();document.getElementById('majalisVoiceOverlay').hidden=false;active=true;setStatus('أجهز المحادثة…','connecting');setDetail('لحظات وأسمعك.');
  try{
    await prepareAudio();const token=await fetchToken();if(!active)return;
    const ai=new GoogleGenAI({apiKey:token,httpOptions:{apiVersion:'v1alpha'}});
    session=await ai.live.connect({
      model:MODEL,
      config:{responseModalities:[Modality.AUDIO],systemInstruction:contextInstruction(),inputAudioTranscription:{},outputAudioTranscription:{},speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:'Kore'}}},tools:[{functionDeclarations:MAJALIS_TOOL_DECLARATIONS}]},
      callbacks:{onopen:()=>setStatus('أتصل بمساعد مجالس…','connecting'),onmessage:handleMessage,onerror:event=>console.error('Majalis voice:',event),onclose:()=>{if(active){setStatus('انقطع الاتصال','error');setDetail('انقطع الاتصال الصوتي. حاول مرة أخرى.')}}}
    });
    if(!active)return;startMic();setStatus('أسمعك الآن','listening');setDetail('تكلم بشكل طبيعي. أقدر أقرأ حالة الاجتماع وأشرحها وأنقلك وأنفذ معك داخل مجالس.');
  }catch(error){console.error('Majalis voice start:',error);setStatus('تعذر تشغيل المحادثة الصوتية','error');setDetail('تعذر الاتصال الآن. حاول مرة أخرى بعد قليل.');try{session?.close?.()}catch{}session=null;active=false;await shutdown()}
}
async function stop(){active=false;try{session?.close?.()}catch{}session=null;await shutdown();emitState('','اضغط وقل ما تريد');const host=document.getElementById('majalisVoiceOverlay');if(host)host.hidden=true}
window.MajalisVoice={start,stop,get active(){return active}};ensureUi();injectStyles();
